const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const path = require('node:path');
const src = path.join(__dirname, 'src');
for (const file of fs.readdirSync(src).filter(x => x.endsWith('.js'))) new vm.Script(fs.readFileSync(path.join(src, file), 'utf8'), {filename:file});
const html = fs.readFileSync(path.join(src, 'vndb_tool.html'), 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
const ctx = vm.createContext({window:{addEventListener(){}}, console, Blob, document:{getElementById(){return {appendChild(){}, classList:{add(){},remove(){}},value:''};}}, navigator:{clipboard:{write:async()=>{}}}, ClipboardItem:class{constructor(data){this.data=data;}}});
vm.runInContext(script, ctx);
for (const value of ['v7724','vn7724','VNDB7724','https://vndb.org/v7724']) assert.equal(ctx.extractId(value),'v7724');
assert.equal(ctx.extractReleaseId('https://vndb.org/r63343'), 'r63343');
assert.equal(ctx.extractReleaseId('R63343'), 'r63343');
assert.equal(ctx.formatReleaseAge(null),null);
assert.equal(ctx.formatReleaseAge(0),'전연령');
assert.equal(ctx.formatReleaseAge(18),'18+');
const vn = {id:'v7724',title:'Test VN',alttitle:'Original',rating:80,votecount:10,developers:[{name:'Developer'}],tags:[]};
const rel = {title:'Release',alttitle:'Original release',released:'2026-01-01',minage:18,languages:[{lang:'ja'}],producers:[{name:'Publisher',publisher:true,developer:true}],vns:[vn]};
const output = ctx.buildReleaseHtml('r63343',rel,'Developer','18+','tag','<p>Description</p>');
for(const text of ['발매일','2026-01-01','https://vndb.org/r63343','detailsContent','Description']) assert.ok(output.includes(text));
assert.ok(!output.includes('<b>별칭</b>'));
const multi = ctx.buildMultiGameTable('v7724',vn,'tag','https://vndb.org/r63343');
assert.ok(multi.includes('https://vndb.org/r63343'));
assert.ok(!multi.includes('<b>발매일</b>'));
assert.ok(ctx.buildHtml('https://vndb.org/v7724','Original','Dev','Pub','Alias',80,10,2,120,'<p>Desc</p>','18+','tag').includes('별칭'));
const ref = vm.createContext({});
vm.runInContext(fs.readFileSync(path.join(src,'release_mode.js'),'utf8'),ref);
for(const name of Object.keys(ref)) if(typeof ref[name]==='function') assert.equal(ref[name].toString().replace(/\s+/g,''),ctx[name].toString().replace(/\s+/g,''), name+' reference parity');
(async()=>{
  ctx.fetch=async()=>({ok:true,json:async()=>({results:[{vns:[{id:'v7724'}]}]})});
  const tokens=await ctx.resolveMultiTokens(ctx.parseMultiUrls('v1, r63343'),()=>{});
  assert.equal(tokens[1].vnId,'v7724');
  assert.equal(tokens[1].displayUrl,'https://vndb.org/r63343');
  ctx.fetchReleaseFull=async()=>rel;
  ctx.fetchVnDescription=async()=> 'Description';
  assert.ok((await ctx.runRelease('r63343','',()=>{})).includes('Description'));
  let clipboard;
  ctx.navigator.clipboard.write=async(items)=>{clipboard=items[0].data;};
  await ctx.copyAsRichText('<p>test</p>');
  assert.ok(clipboard['text/html']);
  console.log('PASS: JavaScript syntax, input parsing, release output and pipeline, mixed input URL preservation, reference parity, rich HTML clipboard. External APIs/GUI not tested.');
})().catch(e=>{console.error(e);process.exitCode=1;});
